### PR TITLE
Add calendar applet

### PR DESCRIPTION
**Pull request by AmazinAxel**
I have added a calendar applet that allows users to view the current date and preview the previous and future months. This applet will be shown in the applet tray on startup.
I also have tested this webtop on multiple different browsers and found that this works perfect with Chromium based browsers, but doesn't work with other browsers such as Firefox. I have updated the info in the readme file to inform users.
Keep up the amazing work on the webtop!

### CODE REVIEW

**Comment by electrikmilk** [comment]
You have a merge commit in your feature branch. Please properly resolve the conflicts with main.

This may be of help: https://stackoverflow.com/questions/67419365/resolving-merge-conflicts-after-reverting-a-merge-commit

**Comment by AmazinAxel** [comment]
Sorry about that, this is my first time trying to do a pull request. I don't really know how this stuff works but I have just tried to copy the new desktop.js code and edit it to add the "calendar" applet on startup. I hope I don't mess anything up by trying to fix the conflicts.

**Comment by electrikmilk** [comment]
I'll work on documenting the integration of an app or applet into the system better — what's required and what's not.

**Comment by electrikmilk** [comment]
> Sorry about that, this is my first time trying to do a pull request. I don't really know how this stuff works but I have just tried to copy the new desktop.js code and edit it to add the "calendar" applet on startup. I hope I don't mess anything up by trying to fix the conflicts.

No worries, you're working on your fork of the project, so as long as everything is correct when I merge your changes, there's no need to worry about making some mistakes here and there.

This was helpful to me in the past when my fork of a repo had fallen behind: https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream

I would make sure your changes are stored somewhere, reset your branch to upstream as shown in the link, commit your changes again, then force push to your branch using `git push --force`. That should get rid of those merge commits.

**Pull request merged**
